server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
    context-path: '/'

spring:
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolioDB
    driverClassName: org.postgresql.Driver
    username: devuser
    password: devpassword
    initialization-mode: always

  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: update
    generate-ddl: true


logging:
  level:
    org:
      springframework:
        web: DEBUG
        servlet: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always